"""initial tables

Revision ID: e5a16c74cbe5
Revises: 
Create Date: 2026-04-05 19:01:34.390438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5a16c74cbe5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'task_manager', 'coder', name='user_role', create_constraint=True), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('online', 'idle', 'offline', 'dnd', name='user_status', create_constraint=True), server_default='offline', nullable=False),
    sa.Column('custom_status', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('chat_groups',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dev_availability',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('base_unavailable_hours', sa.Float(), server_default='11', nullable=False),
    sa.Column('weekly_slots', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='Array[7] of { blocked_slots, available_hours, band }'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('dm_threads',
    sa.Column('user_a', sa.UUID(), nullable=False),
    sa.Column('user_b', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('user_a < user_b', name='ck_dm_threads_user_order'),
    sa.ForeignKeyConstraint(['user_a'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_b'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('auto_name', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('product', 'process', 'meetings', 'finance', 'research', 'legal_hr', 'task_uploads', name='document_category', create_constraint=True), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('upload_origin', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('version_parent_id', sa.UUID(), nullable=True),
    sa.Column('version_number', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_current_version', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_parent_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('task_assigned', 'status_change', 'carry_forward', 'flag_raised', 'flag_resolved', 'chat_mention', 'chat_message', 'deadline_warning', name='notification_type', create_constraint=True), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'in_review', 'completed', 'flagged', 'reassigned', name='task_status', create_constraint=True), server_default='pending', nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='task_priority', create_constraint=True), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('original_deadline', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('current_deadline', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('carry_forward_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('flag_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('original_assignee', sa.UUID(), nullable=True),
    sa.Column('is_frozen', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['original_assignee'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carry_forward_logs',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('carry_number', sa.Integer(), nullable=False),
    sa.Column('from_deadline', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('to_deadline', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('evidence_doc_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_doc_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_group_members',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_muted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notification_pref', sa.Enum('all', 'mentions', 'mute', name='notification_pref', create_constraint=True), server_default='mentions', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['chat_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.create_table('messages',
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('dm_thread_id', sa.UUID(), nullable=True),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Enum('text', 'file', 'code', 'image', 'link', name='message_type', create_constraint=True), nullable=False),
    sa.Column('reply_to_id', sa.UUID(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_edited', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('edited_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('attachment_doc_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attachment_doc_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['dm_thread_id'], ['dm_threads.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['chat_groups.id'], ),
    sa.ForeignKeyConstraint(['reply_to_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress_entries',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.Enum('screenshot', 'document', 'link', 'text_note', 'voice_note', 'code_snippet', 'doc_hub_link', name='progress_entry_type', create_constraint=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_entries_task_id'), 'progress_entries', ['task_id'], unique=False)
    op.create_table('task_assignees',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('contribution_pct', sa.Integer(), server_default='0', nullable=False),
    sa.Column('assigned_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'user_id')
    )
    op.create_table('task_documents',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('link_type', sa.Enum('brief', 'progress', 'reference', name='task_doc_link_type', create_constraint=True), nullable=False),
    sa.Column('linked_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'document_id')
    )
    op.create_table('task_flags',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('flagged_by', sa.UUID(), nullable=False),
    sa.Column('reason_category', sa.Enum('academic', 'personal', 'workload', 'technical', 'other', name='flag_reason_category', create_constraint=True), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=False),
    sa.Column('progress_status', sa.Enum('not_started', 'pct_25', 'pct_50', 'pct_75', name='flag_progress_status', create_constraint=True), nullable=False),
    sa.Column('handoff_notes', sa.Text(), nullable=True),
    sa.Column('estimated_hours_remaining', sa.Float(), nullable=True),
    sa.Column('is_late_flag', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('flag_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending_review', 'resolved_reassigned', 'resolved_extended', 'resolved_rescoped', 'expired', name='flag_status', create_constraint=True), server_default='pending_review', nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flagged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_flags_task_id'), 'task_flags', ['task_id'], unique=False)
    op.create_table('message_reactions',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('emoji', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'user_id', 'emoji')
    )
    op.create_table('reassignment_history',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('from_user', sa.UUID(), nullable=False),
    sa.Column('to_user', sa.UUID(), nullable=False),
    sa.Column('flag_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flag_id'], ['task_flags.id'], ),
    sa.ForeignKeyConstraint(['from_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['to_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reassignment_history')
    op.drop_table('message_reactions')
    op.drop_index(op.f('ix_task_flags_task_id'), table_name='task_flags')
    op.drop_table('task_flags')
    op.drop_table('task_documents')
    op.drop_table('task_assignees')
    op.drop_index(op.f('ix_progress_entries_task_id'), table_name='progress_entries')
    op.drop_table('progress_entries')
    op.drop_table('messages')
    op.drop_table('chat_group_members')
    op.drop_table('carry_forward_logs')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('documents')
    op.drop_table('dm_threads')
    op.drop_table('dev_availability')
    op.drop_table('chat_groups')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
